apiVersion: v2
name: emd-payment-core
description: emd-payment-core app
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
- name: microservice-chart
  version: 7.4.0
  repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
