parameters:
  - name: 'ENV'
    displayName: 'Environment to deploy'
    type: string
    values:
      - dev
      - uat
      - prod
  - name: 'APP_NAME'
    displayName: 'Application to deploy'
    type: string
    values:
      - status
      - emd-message-core


resources:
  repositories:
    - repository: helm
      type: github
      name: pagopa/azure-pipeline-templates
      ref: refs/heads/wrapper-helm-deploy
      endpoint: 'io-azure-devops-github-ro'

pool:
  vmImage: ubuntu-latest

stages:
  - template: templates/helm-microservice-chart-deploy-tree/template.yaml@helm
    parameters:
      DO_DEPLOY: true
      ENV: ${{ parameters.ENV }}
      KUBERNETES_SERVICE_CONN: $(DEV_KUBERNETES_SERVICE_CONN)
      APP_NAME: ${{ parameters.APP_NAME }}
#      NAMESPACE: $(namespace)
#      DEPLOY_VERSION: $(deployversion)


