parameters:
  - name: 'ENV'
    displayName: 'Environment to deploy'
    type: string
    values:
      - dev
      - uat
      - prod
  - name: 'APP_NAME'
    displayName: 'Application to deploy'
    type: string
    values:
      - emd-message-core
      - status

variables:
  - template: .namespace.yml


resources:
  repositories:
    - repository: helm
      type: github
      name: pagopa/azure-pipeline-templates
      ref: refs/heads/wrapper-helm-deploy
      endpoint: 'io-azure-devops-github-ro'

pool:
  vmImage: ubuntu-latest

stages:

  - stage: 'Deploy_for_selected_env'
    displayName: 'Deploy on selected environment'
    condition: succeeded()
    jobs:
      - deployment: "deploy"
        environment: ${{ parameters.ENV }}
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  displayName: "Checkout"
                - template: templates/helm-microservice-chart-deploy-tree/template.yaml@helm
                  parameters:
                    DO_DEPLOY: true
                    ENV: ${{ parameters.ENV }}
                    KUBERNETES_SERVICE_CONN: $(DEV_KUBERNETES_SERVICE_CONN)
                    NAMESPACE: ${{ variables.namespaces.parameters.APP_NAME }}
                    APP_NAME: ${{ parameters.APP_NAME }}
                    DEPLOY_VERSION: $(Build.SourceVersion)


