parameters:
  - name: 'ENV'
    displayName: 'Environment to deploy'
    type: string
    values:
      - dev
      - uat
      - prod
  - name: 'APP_NAME'
    displayName: 'Application to deploy'
    type: string
    values:
      - status
      - emd-message-core

variables:
  ${{ if eq(parameters.ENV, 'uat') }}:
    kubernetesServiceConnection: '$(UAT_KUBERNETES_SERVICE_CONN)'

  ${{ if eq(parameters.ENV, 'prod') }}:
    kubernetesServiceConnection: '$(PROD_KUBERNETES_SERVICE_CONN)'

  ${{ if eq(parameters.ENV, 'dev') }}:
    kubernetesServiceConnection: '$(DEV_KUBERNETES_SERVICE_CONN)'

resources:
  repositories:
    - repository: templates
      type: github
      name: pagopa/azure-pipeline-templates
      ref: refs/tags/v6.7.1
      endpoint: 'io-azure-devops-github-ro'

pool:
  vmImage: ubuntu-latest

stages:
  - template: templates/helm-microservice-chart-deploy-tree/template.yaml@templates
    parameters:
      DO_DEPLOY: true
      ENV: ${{ parameters.ENV }}
      KUBERNETES_SERVICE_CONN: ${{ variables.kubernetesServiceConnection }}
      APP_NAME: ${{ parameters.APP_NAME }}
      CHART_PATH: "helm/${{parameters.ENV}}/${{parameters.APP_NAME}}"
      VALUE_FILE: "helm/${{parameters.ENV}}/${{parameters.APP_NAME}}/values.yaml"
