parameters:
  - name: 'ENV'
    displayName: 'Environment to deploy'
    type: string
    values:
      - dev
      - uat
      - prod
  - name: 'APP_NAME'
    displayName: 'Application to deploy'
    type: string
    values:
      - status
      - emd-message-core
      - mil-papos

variables:
  ${{ if eq(parameters.ENV, 'uat') }}:
    kubernetesServiceConnection: '$(UAT_KUBERNETES_SERVICE_CONN)'
    selfHostedAgentPool: '$(UAT_AGENT_POOL)'

  ${{ if eq(parameters.ENV, 'prod') }}:
    kubernetesServiceConnection: '$(PROD_KUBERNETES_SERVICE_CONN)'
    selfHostedAgentPool: '$(PROD_AGENT_POOL)'

  ${{ if eq(parameters.ENV, 'dev') }}:
    kubernetesServiceConnection: '$(DEV_KUBERNETES_SERVICE_CONN)'
    selfHostedAgentPool: '$(DEV_AGENT_POOL)'

resources:
  repositories:
    - repository: templates
      type: github
      name: pagopa/azure-pipeline-templates
      ref: refs/tags/v6.8.0
      endpoint: 'io-azure-devops-github-ro'

pool:
  name: $(selfHostedAgentPool)

name: "Deploy ${{ parameters.APP_NAME }} on ${{ parameters.ENV }} - $(Date:yyyyMMdd).$(Rev:r)"

stages:
  - template: templates/helm-microservice-chart-deploy-tree/template.yaml@templates
    parameters:
      ENV: ${{ parameters.ENV }}
      KUBERNETES_SERVICE_CONN: ${{ variables.kubernetesServiceConnection }}
      APP_NAME: ${{ parameters.APP_NAME }}
      CHART_PATH: "helm/${{parameters.ENV}}/${{parameters.APP_NAME}}"
      VALUE_FILE: "helm/${{parameters.ENV}}/${{parameters.APP_NAME}}/values.yaml"

  - stage: postman_tests
    displayName: 🔦 Run Postman Tests
    dependsOn: [ ]
    condition: succeeded()
    jobs:
      - job: run_postman_tests_job
        displayName: Run Postman Tests
        steps:
        - task: UseNode@1
          inputs:
            version: '18.16.0'
        - script: |
            git clone https://github.com/pagopa/mil-papos.git
            cd mil-papos/src/test/postman
            npm install -g newman
            newman run mil-papos.postman_collection.json -e dev.postman_environment.json