parameters:
  - name: 'ENV'
    displayName: 'Environment to deploy'
    type: string
    values:
      - dev
      - uat
      - prod
  - name: 'APP_NAME'
    displayName: 'Application to deploy'
    type: string
    values:
      - status
      - emd-message-core

variables:
  - template: .namespace.yml


resources:
  repositories:
    - repository: helm
      type: github
      name: pagopa/azure-pipeline-templates
      ref: refs/heads/wrapper-helm-deploy
      endpoint: 'io-azure-devops-github-ro'

pool:
  vmImage: ubuntu-latest

stages:

  - stage: 'Deploy_for_selected_env'
    displayName: 'Deploy on selected environment'
    condition: succeeded()
    jobs:
      - deployment: "deploy_${{ parameters.APP_NAME }}_${{ parameters.ENV }}"
        displayName: "Deploy ${{ parameters.APP_NAME }} on ${{ parameters.ENV }}"
        environment: ${{ parameters.ENV }}
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  displayName: "Checkout"
                - task: Bash@3
                  displayName: 'Set namespace variables'
                  inputs:
                    targetType: 'inline'
                    script: |
                      echo "path name: $(Build.Repository.LocalPath)/helm/${{parameters.ENV}}/${{parameters.ENV}}"
                      echo "##vso[task.setvariable variable=namespace]$(yq read $(Build.Repository.LocalPath)/helm/${{parameters.ENV}}/${{parameters.ENV}}/values.yaml 'namespace' )"
                      echo "namespace: $(namespace)"
                - template: templates/helm-microservice-chart-deploy-tree/template.yaml@helm
                  parameters:
                    DO_DEPLOY: true
                    ENV: ${{ parameters.ENV }}
                    KUBERNETES_SERVICE_CONN: $(DEV_KUBERNETES_SERVICE_CONN)
                    NAMESPACE: $(namespace)
                    APP_NAME: ${{ parameters.APP_NAME }}
                    DEPLOY_VERSION: $(Build.SourceVersion)


