apiVersion: v2
name: emd-message-core
description: emd-message-core app
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
- name: microservice-chart
  version: 5.9.1
  repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
